export default {
  balanceCards: {
	    title: 'My Balance Cards', description: 'View daily, weekly, and total allowances on your balance cards', empty: 'No balance cards', emptyHint: 'Balance cards assigned by an administrator will appear here.', days: 'days', expiresAt: 'Expires', todayQuota: "Today's allowance", quotaUsage: 'Allowance usage', weekQuota: 'Weekly allowance', weekCardTotal: 'Week-card total', monthCardTotal: 'Month-card total', unlimited: 'Unlimited', quotaUnlimited: 'This allowance is unlimited', remaining: '${amount} remaining today', quotaRemaining: '${amount} remaining',
    fallback: 'Use cash balance when exhausted', fallbackHint: 'Cash balance is used when any daily, weekly, or total allowance is exhausted.', autoReset: 'Auto-reset when exhausted', autoResetHint: 'A daily reset consumes one validity day. When a month card reaches its weekly limit, the remainder of the current week is consumed to start the next week early.', resetCount: 'Reset {current}/{max} times', resetToday: "Reset today's allowance", resetConfirm: 'This reset consumes one validity day. Continue?', resetSuccess: 'Daily allowance reset; one validity day was consumed', resetWeek: 'Start next week early', resetWeekConfirm: 'The weekly allowance is exhausted. Starting the next week early consumes the remainder of this week (about {days} days) and restores the daily and weekly allowances; the month-card total is not reset. Continue?', resetWeekSuccess: 'The next week started early and the remaining current-week validity was consumed', resetFailed: 'Reset failed', loadFailed: 'Failed to load balance cards', saveFailed: 'Failed to save balance-card settings', ledger: 'Activity', event: 'Event', amount: 'Amount', usageAfter: 'Usage after', time: 'Time',
    types: { day: 'Day card', week: 'Week card', month: 'Month card', custom: 'Custom card' },
    status: { pending: 'Pending', active: 'Active', expired: 'Expired', suspended: 'Suspended', revoked: 'Revoked' },
    events: { assign: 'Assigned', activate: 'Activated', usage: 'Usage', natural_reset: 'Daily reset', manual_reset: 'Manual reset', auto_reset: 'Auto reset', extend: 'Validity adjusted', revoke: 'Revoked', restore: 'Restored', preference_update: 'Preferences updated' },
    admin: {
	      title: 'Balance Card Management', description: 'Manage balance-card plans and user assignments', issuedCards: 'User cards', plans: 'Plans', assign: 'Assign card', createPlan: 'Create plan', editPlan: 'Edit plan', userId: 'User ID', user: 'User', plan: 'Plan', allPlans: 'All plans', allStatus: 'All statuses', total: '{count} total', extend: 'Adjust', revoke: 'Revoke', validity: 'Validity days', dailyQuota: 'Daily allowance', planDescription: 'Description', cardType: 'Card type', maxResets: 'Maximum resets', sortOrder: 'Sort order', unlimitedQuotaHint: 'Leave blank or enter 0 for unlimited', userIds: 'Select users', userIdsHint: 'Search by email or username', userSearchPlaceholder: 'Search username or email', userSearchEmpty: 'No selectable users found', selectedUsers: '{count} users selected', removeUser: 'Remove user', unnamedUser: 'No username', userIdFallback: 'User #{id}', notes: 'Notes', queueHint: 'If a user already has an active card, the new card is queued and starts after it expires.', invalidUsers: 'Select users and a plan', assignSuccess: 'Assigned cards to {count} users', assignFailed: 'Assignment failed', extendPrompt: 'Enter the number of days to adjust (negative shortens)', invalidDays: 'Enter a non-zero whole number of days', revokeConfirm: 'Revoke this balance card? Queued cards will be moved forward.', deleteConfirm: 'Deleting hides this card from both admin and user lists while retaining billing and audit history. Delete it?', deleteSuccess: 'Balance card deleted', deleteFailed: 'Failed to delete balance card'
    }
  }
}
